listfile = 'files.txt' # format: string    path/to/file - the string must be unique in the list, it works like a combination of tags + title, and is searchable
cssjs = 'E:/Note-/style.css'
outfolder = 'E:/Note-/html/' # will generate if not exist
zipfolder = 'E:/Note-/backup/' # local backup folder
upfolder = '/Note-/' # assign a folder on your FTP/WebDAV for Note-
te = 'D:/Progra~1/EmEditor/EmEditor.exe'
pandoc = 'pandoc.exe'
szip = '7z.exe'
WinSCP = 'winscp.com'
server = 'https://usernameoremail:password@dav.example.com/'
password = 'yourpassword'
snname = 'youremail'
snpwd = 'yourpassword'
snkeylist = 'E:/Note-/snkey.txt' # store keys here
